### ISSUE TITLE
Option to disable restart prompt on icon change.

### ISSUE THREAD

**Issue by Eapzy** [SteamGridDB/decky-steamgriddb#85]
I find myself frequently accidentally saying yes to this (as it is the default option) and an option to disable the prompt would be awesome.

**Comment by doZennn** [comment]
Not restarting invalidates changes the plugin makes to `shortcuts.vdf` when anything in the client makes a change to any data on non-Steam shortcuts.  
People already frequently ask why their icons don't change, and the answer is always because they press "Later". Adding an option like this would just increase the amount of these support questions and I don't want to deal with that.
